server:
  port: 9090

spring:
  application:
    name: article
  datasource:
    dynamic:
      primary: master
      strict: true
      datasource:
        master:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/blog
          username: root
          password: root
  mvc:
    path match:
      matching-strategy: ant_path_matcher


