server:
  port: 8080

spring:
  application:
    name: id-generation
  datasource:
    dynamic:
      hikari:
        maximum-pool-size: 10
        minimum-idle: 5
        idle-timeout: 30000
        pool-name: Hikari-CP
      primary: master
      strict: true
      datasource:
        master:
          driverClassName: com.mysql.jdbc.Driver
          url: jdbc:mysql://localhost:3306/blog
          username: root
          password: root
          hikari:
            maximum-pool-size: 10
            minimum-idle: 5
            idle-timeout: 30000
            connection-timeout: 30000
            pool-name: Hikari-CP-master
  mvc:
    path match:
      matching-strategy: ant_path_matcher


